baseURL = 'https://dualq.io/'
languageCode = 'en-us'
title = 'coming soon'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

[params]
name = "Coming Soon"
location = "Buenos Aires, Argentina"
description = "We're under construction. Please check back for an update soon."
github = "https://github.com/dualqio"
github_username = "dualqio"
email = "hello@dualq.io"

[[params.projects]]
title = "Project Consectetur"
description = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam."
tech = "Python, TensorFlow, Docker, Redis"
image = "/images/projects/consectetur.png"
link = "https://github.com/loremipsum/consectetur"


[[params.blogs]]
title = "Lorem Ipsum Systems"
date = "2025-03-15"
summary = "Sed ut perspiciatis unde omnis iste natus error sit voluptatem."
tags = ["Lorem", "Ipsum", "Dolor"]
content = """
Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit...
"""
link = "https://medium.com/@loremipsum/lorem-systems"

[menu]
  [[menu.main]]
    name = "Contact Us"
    url = "mailto:hello@dualq.io"
    weight = 5